sudo: false

language: c

matrix:
  include:
    - env: GHCVER=7.6.3 CABALVER=2.4
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.6.3
            - cabal-install-2.4
    - env: GHCVER=7.8.4 CABALVER=2.4
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.8.4
            - cabal-install-2.4
    - env: GHCVER=7.10.3 CABALVER=2.4
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.10.3
            - cabal-install-2.4
    - env: GHCVER=8.0.2 CABALVER=2.4
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - cabal-install-2.4
    - env: GHCVER=8.2.1 CABALVER=2.4
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.2.1
            - cabal-install-2.4
    - env: GHCVER=8.4.4 CABALVER=2.4
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.4.4
            - cabal-install-2.4
    - env: GHCVER=8.6.3 CABALVER=2.4
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.6.3
            - cabal-install-2.4
    - env: GHCVER=8.8.1 CABALVER=3.0
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.8.1
            - cabal-install-3.0
    - env: GHCVER=8.10.1 CABALVER=head
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.10.1
            - cabal-install-head
    - env: GHCVER=head CABALVER=head
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-head
            - cabal-install-head
  allow_failures:
    - env: GHCVER=head CABALVER=head
    - env: GHCVER=8.10.1 CABALVER=head

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - CABAL_OPTS=""
  - |
    case "$GHCVER" in
    head | 8.10.1 )
      CABAL_OPTS="$CABAL_OPTS --allow-newer"
      ;;
    esac
  - ghc --version
  - cabal --version
  - travis_retry cabal v1-update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
  - cabal v1-install --enable-tests --only-dep $CABAL_OPTS

script:
  - (cd ghci-wrapper && cabal v1-configure --enable-tests --ghc-options=-Werror $CABAL_OPTS && cabal v1-build && cabal v1-test)
  - cabal v1-configure --enable-tests --ghc-options=-Werror $CABAL_OPTS && cabal v1-build && cabal v1-test
